---
- name: Spin up some EC2 instances
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Launch instances
      local_action:
        module: ec2
        region: eu-west-1
        keypair: mminar-pulp
        group: pulp
        instance_type: m3.large
        image: ami-a5ad56d2
        count: 3
        wait: yes
      register: ec2

    - name: Tag instances
      local_action: ec2_tag resource= region=eu-west-1 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: mminar

    - name: Give everyone a minute
      pause: minutes=1
