---
- name: Spin up some EC2 instances
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Launch instances
      local_action:
        module: ec2
        # regions: us-east-1, us-west-1, us-west-2, eu-west-1, ap-northeast-1 ..
        region: eu-west-1
        # insert your key in selected region
        keypair: myname-eu-west-1
        group: pulp
        instance_type: m3.large
        # insert ami for OS you want to install eg. for Fedora 20 its ami-a5ad56d2
        image: ami-a5ad56d2
        count: 3
        wait: yes
      register: ec2

    - name: Tag instances
      local_action: ec2_tag resource={{ item.id }} region=eu-west-1 state=present
      with_items: ec2.instances
      args:
        tags:
          # to be able find all your instances
          Name: myname

    - name: Give everyone a minute
      pause: minutes=1
