- name: copy repo file
  copy: src=roles/common/files/{{ansible_distribution}}-pulp.repo dest=/etc/yum.repos.d/pulp.repo owner=root group=root mode=0644

- name: install pulp consumer
  yum: name=@pulp-consumer state=latest

- name: configure pulp consumer
  template: src=consumer.conf.j2 dest=/etc/pulp/consumer/consumer.conf mode=0643

- name: start pulp consumer service
  service: name=goferd state=restarted enabled=yes
