- job-template:
    name: '{name}-pulp-automation'
    project-type:  freestyle
    defaults: global
    display-name: "{name} pulp automation job"
    concurent: True
    quiet-period: 0
    parameters:
    - file:
        name: nosetests.xml
        description: nosetests xunit test result file
    - file:
        name: coverage.xml
        description: nosetests coverage result file
    publishers:
    - junit:
        results: nosetests.xml
    - cobertura:
        report-file: coverage.xml
        targets:
            - files:
                healthy: 0
                unhealthy: 0
                failing: 0
            - method:
                healthy: 0
                unhealthy: 0
                failing: 0

- project:
    name: single-node
    jobs:
      - '{name}-pulp-automation':
